# SweepFunction Examples

In [1]:
using SweepFunction

In [2]:
? SweepFunction

search: SweepFunction



Automatic sweeping of function evaluations over a sample space.

# AUTHORSHIP

```
* Author    : Eduardo J. Alvarez
* Email     : Edo.AlvarezR@gmail.com
* Created   : Nov 2018
* License   : MIT
```


## Basic Setup

In [3]:
? ArgSweep

search: ArgSweep



`ArgSweep{T}(arg::Symbol, vals::Array{T, 1})`

Defines an argument `arg` to sweep and the set of values `vals` that the argument will take.

NOTE: This is only for optional (keyword) arguments.


In [4]:
? Sweep

search: Sweep SweepFunction ArgSweep runsweep printsweep



`Sweep(fun::Function, argsweep::Array{ArgSweep, 1}, cons_args::Array{Any, 1}, cons_optargs::Array{Tuple{Symbol, Any}, 1})`

Defines a sweep of function `fun` over multiple arguments `argsweep` with constant required and optional arguments `cons_args` and `cons_optargs` (if none, `cons_args` and `cons_optargs` can be omitted)


In [3]:
# Function to be swept
function fun(; arg1=1.0, arg2=1.0, arg3=1.0)
    return arg1*arg2*arg3
end

# Arguments to sweep (Symbol, values): Sweeps only two arguments
arg_sweep1 = ArgSweep{Int64}(:arg1, [1, 2, 3])
arg_sweep2 = ArgSweep{Float64}(:arg2, [4.0, 5.0])

arg_sweeps = [arg_sweep1, arg_sweep2]

# Defines the sweep
sweep = Sweep(fun, arg_sweeps);

In [5]:
? get_nevals

search: get_nevals



`get_nevals(self::Sweep)`

Returns the number of function evaluations this sweep will take.


In [4]:
get_nevals(sweep)

6

In [6]:
? runsweep

search: runsweep



`runsweep(self::Sweep)`

Runs the sweep evaluation of the function.

```jldoctest
julia> function fun(cons1, cons2; arg1=1.0, arg2=1.0, arg3=1.0)
           return arg1*arg2*arg3 + cons1 + cons2
       end;

julia> arg_sweep1 = ArgSweep{Int64}(:arg1, [1, 2, 3]);

julia> arg_sweep2 = ArgSweep{Float64}(:arg2, [4.0, 5.0]);

julia> arg_sweeps = [arg_sweep1, arg_sweep2];

julia> cons_args = [10, 20];

julia> sweep = Sweep(fun, arg_sweeps, cons_args);

julia> res = runsweep(sweep);

julia> printsweep(res)

"f(10, 20; arg1=1, arg2=4.0) = 34.0

f(10, 20; arg1=2, arg2=4.0) = 38.0

f(10, 20; arg1=3, arg2=4.0) = 42.0

f(10, 20; arg1=1, arg2=5.0) = 35.0

f(10, 20; arg1=2, arg2=5.0) = 40.0

f(10, 20; arg1=3, arg2=5.0) = 45.0
"
```


In [7]:
# Runs the sweep
res = runsweep(sweep)

6-element Array{Any,1}:
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 1), (:arg2, 4.0)]),Pair{String,Any}("arguments", Any[]),Pair{String,Any}("result", 4.0)) 
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 2), (:arg2, 4.0)]),Pair{String,Any}("arguments", Any[]),Pair{String,Any}("result", 8.0)) 
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 3), (:arg2, 4.0)]),Pair{String,Any}("arguments", Any[]),Pair{String,Any}("result", 12.0))
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 1), (:arg2, 5.0)]),Pair{String,Any}("arguments", Any[]),Pair{String,Any}("result", 5.0)) 
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 2), (:arg2, 5.0)]),Pair{String,Any}("arguments", Any[]),Pair{String,Any}("result", 10.0))
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 3), (:arg2, 5.0)]),Pair{Stri

In [8]:
? printsweep

search: printsweep



`printsweep(runsweep_output; verbose=true, lvl=0)`

Given the output of `runsweep()`, it will format it and print it as a string.


In [9]:
printsweep(res);

f(; arg1=1, arg2=4.0) = 4.0
f(; arg1=2, arg2=4.0) = 8.0
f(; arg1=3, arg2=4.0) = 12.0
f(; arg1=1, arg2=5.0) = 5.0
f(; arg1=2, arg2=5.0) = 10.0
f(; arg1=3, arg2=5.0) = 15.0



## Passing Constant Arguments

In [10]:
# Function to be swept
function fun(cons1, cons2; arg1=1.0, arg2=1.0, arg3=1.0)
    return arg1*arg2*arg3 + cons1 + cons2
end

# Arguments to sweep (Symbol, values): Sweeps only two arguments
arg_sweep1 = ArgSweep{Int64}(:arg1, [1, 2, 3])
arg_sweep2 = ArgSweep{Float64}(:arg2, [4.0, 5.0])

arg_sweeps = [arg_sweep1, arg_sweep2]

# Constant required arguments [cons1, cons2]
cons_args = [10, 20]

# Defines the sweep
sweep = Sweep(fun, arg_sweeps, cons_args)

# Runs the sweep
res = runsweep(sweep)

6-element Array{Any,1}:
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 1), (:arg2, 4.0)]),Pair{String,Any}("arguments", Any[10, 20]),Pair{String,Any}("result", 34.0))
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 2), (:arg2, 4.0)]),Pair{String,Any}("arguments", Any[10, 20]),Pair{String,Any}("result", 38.0))
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 3), (:arg2, 4.0)]),Pair{String,Any}("arguments", Any[10, 20]),Pair{String,Any}("result", 42.0))
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 1), (:arg2, 5.0)]),Pair{String,Any}("arguments", Any[10, 20]),Pair{String,Any}("result", 35.0))
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 2), (:arg2, 5.0)]),Pair{String,Any}("arguments", Any[10, 20]),Pair{String,Any}("result", 40.0))
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1

In [11]:
printsweep(res);

f(10, 20; arg1=1, arg2=4.0) = 34.0
f(10, 20; arg1=2, arg2=4.0) = 38.0
f(10, 20; arg1=3, arg2=4.0) = 42.0
f(10, 20; arg1=1, arg2=5.0) = 35.0
f(10, 20; arg1=2, arg2=5.0) = 40.0
f(10, 20; arg1=3, arg2=5.0) = 45.0



In [12]:
# Function to be swept
function fun(cons1, cons2; arg1=1.0, arg2=1.0, arg3=1.0, arg4=1.0)
    return arg1*arg2*arg3*arg4 + cons1 + cons2
end

# Arguments to sweep (Symbol, values): Sweeps only two arguments
arg_sweep1 = ArgSweep{Int64}(:arg1, [1, 2, 3])
arg_sweep2 = ArgSweep{Float64}(:arg2, [4.0, 5.0])

arg_sweeps = [arg_sweep1, arg_sweep2]

# Constant required arguments [cons1, cons2]
cons_args = [10, 20]

# Constant optional arguments [(Symbol, val)]
cons_optargs = [(:arg3, 10), (:arg4, 100)]

# Defines the sweep
sweep = Sweep(fun, arg_sweeps, cons_args, cons_optargs)

# Runs the sweep
res = runsweep(sweep)

6-element Array{Any,1}:
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 1), (:arg2, 4.0), (:arg3, 10), (:arg4, 100)]),Pair{String,Any}("arguments", Any[10, 20]),Pair{String,Any}("result", 4030.0)) 
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 2), (:arg2, 4.0), (:arg3, 10), (:arg4, 100)]),Pair{String,Any}("arguments", Any[10, 20]),Pair{String,Any}("result", 8030.0)) 
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 3), (:arg2, 4.0), (:arg3, 10), (:arg4, 100)]),Pair{String,Any}("arguments", Any[10, 20]),Pair{String,Any}("result", 12030.0))
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 1), (:arg2, 5.0), (:arg3, 10), (:arg4, 100)]),Pair{String,Any}("arguments", Any[10, 20]),Pair{String,Any}("result", 5030.0)) 
 Dict{String,Any}(Pair{String,Any}("optional_arguments", Tuple{Symbol,Any}[(:arg1, 2), (:arg2, 5.0), (:arg3, 10), (:arg4, 100)]),Pair{String

In [13]:
printsweep(res);

f(10, 20; arg1=1, arg2=4.0, arg3=10, arg4=100) = 4030.0
f(10, 20; arg1=2, arg2=4.0, arg3=10, arg4=100) = 8030.0
f(10, 20; arg1=3, arg2=4.0, arg3=10, arg4=100) = 12030.0
f(10, 20; arg1=1, arg2=5.0, arg3=10, arg4=100) = 5030.0
f(10, 20; arg1=2, arg2=5.0, arg3=10, arg4=100) = 10030.0
f(10, 20; arg1=3, arg2=5.0, arg3=10, arg4=100) = 15030.0



## Argument Types

In [14]:
# Function to be swept
function fun(verb::String ; person::String="John", relation::String="friend", 
                num::Int64=1, direction::Array{T,1}=[1, 0, 0]) where {T<:Real}
    return "My $relation $person $verb $num times in the direction $direction\n"
end

# Arguments to sweep (Symbol, values)
arg_sweep1 = ArgSweep{String}(:person, ["John", "James"])
arg_sweep2 = ArgSweep{String}(:relation, ["friend", "enemy"])
arg_sweep3 = ArgSweep{Array}(:direction, [[1, 1, 0], [0, 0, 1]])

arg_sweeps = [arg_sweep1, arg_sweep2, arg_sweep3]

# Constant required arguments [cons1, cons2]
cons_args = ["shot"]

# Constant optional arguments [(Symbol, val)]
cons_optargs = [(:num, 3)]

# Defines the sweep
sweep = Sweep(fun, arg_sweeps, cons_args, cons_optargs)

# Runs the sweep
res = runsweep(sweep)

# Prints the sweep
printsweep(res; newln=true);

f(shot; person=John, relation=friend, direction=[1, 1, 0], num=3)
	 = My friend John shot 3 times in the direction [1, 1, 0]

f(shot; person=James, relation=friend, direction=[1, 1, 0], num=3)
	 = My friend James shot 3 times in the direction [1, 1, 0]

f(shot; person=John, relation=enemy, direction=[1, 1, 0], num=3)
	 = My enemy John shot 3 times in the direction [1, 1, 0]

f(shot; person=James, relation=enemy, direction=[1, 1, 0], num=3)
	 = My enemy James shot 3 times in the direction [1, 1, 0]

f(shot; person=John, relation=friend, direction=[0, 0, 1], num=3)
	 = My friend John shot 3 times in the direction [0, 0, 1]

f(shot; person=James, relation=friend, direction=[0, 0, 1], num=3)
	 = My friend James shot 3 times in the direction [0, 0, 1]

f(shot; person=John, relation=enemy, direction=[0, 0, 1], num=3)
	 = My enemy John shot 3 times in the direction [0, 0, 1]

f(shot; person=James, relation=enemy, direction=[0, 0, 1], num=3)
	 = My enemy James shot 3 times in the direction [0,

## Arbitrary Number of Arguments

In [15]:
function fun(args...; optargs...)
   out = 0
   for arg in args
       out += arg
   end
   for (sym, optarg) in optargs
       out *= optarg
   end
   return out
end

# Arguments to sweep (Symbol, values): Sweeps only two arguments
arg_sweep1 = ArgSweep{Int64}(:arg1, [1, 2, 3])
arg_sweep2 = ArgSweep{Float64}(:arg2, [4.0, 5.0])

arg_sweeps = [arg_sweep1, arg_sweep2]

# Constant required arguments [cons1, cons2]
cons_args = [10, 20]

# Constant optional arguments [(Symbol, val)]
cons_optargs = [(:arg3, 10), (:arg4, 100)]

# Defines the sweep
sweep = Sweep(fun, arg_sweeps, cons_args, cons_optargs)

# Runs the sweep
res = runsweep(sweep)

# Prints the sweep
printsweep(res);

f(10, 20; arg1=1, arg2=4.0, arg3=10, arg4=100) = 4030.0
f(10, 20; arg1=2, arg2=4.0, arg3=10, arg4=100) = 8030.0
f(10, 20; arg1=3, arg2=4.0, arg3=10, arg4=100) = 12030.0
f(10, 20; arg1=1, arg2=5.0, arg3=10, arg4=100) = 5030.0
f(10, 20; arg1=2, arg2=5.0, arg3=10, arg4=100) = 10030.0
f(10, 20; arg1=3, arg2=5.0, arg3=10, arg4=100) = 15030.0

